
package net.readify.knockknock;

import javax.xml.ws.WebFault;
import org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ArgumentOutOfRangeException", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class IRedPillFibonacciNumberArgumentOutOfRangeExceptionFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ArgumentOutOfRangeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IRedPillFibonacciNumberArgumentOutOfRangeExceptionFaultFaultMessage(String message, ArgumentOutOfRangeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IRedPillFibonacciNumberArgumentOutOfRangeExceptionFaultFaultMessage(String message, ArgumentOutOfRangeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.system.ArgumentOutOfRangeException
     */
    public ArgumentOutOfRangeException getFaultInfo() {
        return faultInfo;
    }

}
