
package net.readify.knockknock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRedPill", targetNamespace = "http://KnockKnock.readify.net")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    net.readify.knockknock.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface IRedPill {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WhatIsYourToken", action = "http://KnockKnock.readify.net/IRedPill/WhatIsYourToken")
    @WebResult(name = "WhatIsYourTokenResult", targetNamespace = "http://KnockKnock.readify.net")
    @RequestWrapper(localName = "WhatIsYourToken", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.WhatIsYourToken")
    @ResponseWrapper(localName = "WhatIsYourTokenResponse", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.WhatIsYourTokenResponse")
    public String whatIsYourToken();

    /**
     * 
     * @param n
     * @return
     *     returns java.lang.Long
     * @throws IRedPillFibonacciNumberArgumentOutOfRangeExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "FibonacciNumber", action = "http://KnockKnock.readify.net/IRedPill/FibonacciNumber")
    @WebResult(name = "FibonacciNumberResult", targetNamespace = "http://KnockKnock.readify.net")
    @RequestWrapper(localName = "FibonacciNumber", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.FibonacciNumber")
    @ResponseWrapper(localName = "FibonacciNumberResponse", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.FibonacciNumberResponse")
    public Long fibonacciNumber(
        @WebParam(name = "n", targetNamespace = "http://KnockKnock.readify.net")
        Long n)
        throws IRedPillFibonacciNumberArgumentOutOfRangeExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param a
     * @param b
     * @param c
     * @return
     *     returns net.readify.knockknock.TriangleType
     */
    @WebMethod(operationName = "WhatShapeIsThis", action = "http://KnockKnock.readify.net/IRedPill/WhatShapeIsThis")
    @WebResult(name = "WhatShapeIsThisResult", targetNamespace = "http://KnockKnock.readify.net")
    @RequestWrapper(localName = "WhatShapeIsThis", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.WhatShapeIsThis")
    @ResponseWrapper(localName = "WhatShapeIsThisResponse", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.WhatShapeIsThisResponse")
    public TriangleType whatShapeIsThis(
        @WebParam(name = "a", targetNamespace = "http://KnockKnock.readify.net")
        Integer a,
        @WebParam(name = "b", targetNamespace = "http://KnockKnock.readify.net")
        Integer b,
        @WebParam(name = "c", targetNamespace = "http://KnockKnock.readify.net")
        Integer c);

    /**
     * 
     * @param s
     * @return
     *     returns java.lang.String
     * @throws IRedPillReverseWordsArgumentNullExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ReverseWords", action = "http://KnockKnock.readify.net/IRedPill/ReverseWords")
    @WebResult(name = "ReverseWordsResult", targetNamespace = "http://KnockKnock.readify.net")
    @RequestWrapper(localName = "ReverseWords", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.ReverseWords")
    @ResponseWrapper(localName = "ReverseWordsResponse", targetNamespace = "http://KnockKnock.readify.net", className = "net.readify.knockknock.ReverseWordsResponse")
    public String reverseWords(
        @WebParam(name = "s", targetNamespace = "http://KnockKnock.readify.net")
        String s)
        throws IRedPillReverseWordsArgumentNullExceptionFaultFaultMessage
    ;

}
