
package net.readify.knockknock;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RedPill", targetNamespace = "http://KnockKnock.readify.net", wsdlLocation = "http://knockknock.readify.net/RedPill.svc?wsdl")
public class RedPill
    extends Service
{

    private final static URL REDPILL_WSDL_LOCATION;
    private final static WebServiceException REDPILL_EXCEPTION;
    private final static QName REDPILL_QNAME = new QName("http://KnockKnock.readify.net", "RedPill");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://knockknock.readify.net/RedPill.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REDPILL_WSDL_LOCATION = url;
        REDPILL_EXCEPTION = e;
    }

    public RedPill() {
        super(__getWsdlLocation(), REDPILL_QNAME);
    }

    public RedPill(WebServiceFeature... features) {
        super(__getWsdlLocation(), REDPILL_QNAME, features);
    }

    public RedPill(URL wsdlLocation) {
        super(wsdlLocation, REDPILL_QNAME);
    }

    public RedPill(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REDPILL_QNAME, features);
    }

    public RedPill(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RedPill(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRedPill
     */
    @WebEndpoint(name = "BasicHttpBinding_IRedPill")
    public IRedPill getBasicHttpBindingIRedPill() {
        return super.getPort(new QName("http://KnockKnock.readify.net", "BasicHttpBinding_IRedPill"), IRedPill.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRedPill
     */
    @WebEndpoint(name = "BasicHttpBinding_IRedPill")
    public IRedPill getBasicHttpBindingIRedPill(WebServiceFeature... features) {
        return super.getPort(new QName("http://KnockKnock.readify.net", "BasicHttpBinding_IRedPill"), IRedPill.class, features);
    }

    /**
     * 
     * @return
     *     returns IRedPill
     */
    @WebEndpoint(name = "BasicHttpsBinding_IRedPill")
    public IRedPill getBasicHttpsBindingIRedPill() {
        return super.getPort(new QName("http://KnockKnock.readify.net", "BasicHttpsBinding_IRedPill"), IRedPill.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRedPill
     */
    @WebEndpoint(name = "BasicHttpsBinding_IRedPill")
    public IRedPill getBasicHttpsBindingIRedPill(WebServiceFeature... features) {
        return super.getPort(new QName("http://KnockKnock.readify.net", "BasicHttpsBinding_IRedPill"), IRedPill.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REDPILL_EXCEPTION!= null) {
            throw REDPILL_EXCEPTION;
        }
        return REDPILL_WSDL_LOCATION;
    }

}
